name: Servercore Container Build and Push

on:
  push:
    tags:
      - v1.*

jobs:
  build-and-deploy:
    runs-on: windows-2019
    env:
      RUNNER_VERSION: 2.291.1

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Dockerfile
        run: docker build -t ghcr.io/antgrutta/winrunner:${{ github.ref_name }} --build-arg RUNNER_VERSION=${{env.RUNNER_VERSION}} .

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/antgrutta/winrunner:${{ github.ref_name }}
